version: 2
sphinx:
  configuration: docs/source/conf.py
formats:
  - epub
  - pdf
python:
  install:
    # install itself with pip install .
    - method: pip
      path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
