name: Test downstream projects

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build
        python -m build .
        pip install dist/traitlets*.whl
        pip install --pre --upgrade traitlets[test] pytest pytest-cov
        pip install ipython[test] git+https://github.com/jupyter/nbconvert.git#egg=nbconvert[test] \
                    notebook[test] ipywidgets[test]
        pip freeze

    - name: Run tests IPython
      run: |
        pytest --cov traitlets --cov-report=xml:coverage-from-nbconvert.xml \
               --pyargs IPython -p no:unraisableexception 
    - name: Run tests nbconvert
      run: |
        pytest --cov traitlets --cov-report=xml:coverage-from-nbconvert.xml \
               --pyargs nbconvert -p no:unraisableexception -k 'not network'
    - name: Run tests notebook
      run: |
        pytest --cov traitlets --cov-report=xml:coverage-from-notebook.xml \
               --pyargs notebook -k 'not selenium and not integration_tests'
    - name: Run tests ipywidgets
      run: |
        pytest --cov traitlets --cov-report=xml:coverage-from-ipywidgets.xml \
               --pyargs ipywidgets

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
